name: "certgen"
version: "1.0"
usage: "Self signed certificates generation"
description: |-
  This plugin generates self signed certificate for route (Openshift) and in form of secret for Ingress (k8s)

  Usage:

  > helm certgen install onesaitplatform/onesait-platform-chart \
               --namespace onesait-platform \
               --generate-name \
               --version 2

  or simply

  > helm certgen
ignoreFlags: false
command: "$HELM_PLUGIN_DIR/create-certs-fullchain.sh"
hooks:
  install: "cd $HELM_PLUGIN_DIR; scripts/install_plugin.sh"
  update: "cd $HELM_PLUGIN_DIR; scripts/install_plugin.sh"
